module Codeme
  # Type Code
  TYPE_CODE_SYSTEM = 0 << 3
  TYPE_CODE_AUTH = 1 << 3
  TYPE_CODE_RFID = 3 << 3
  TYPE_CODE_BUZZER = 4 << 3


  # System Action
  ACTION_CODE_SYSTEM_POWEROFF = 0
  ACTION_CODE_SYSTEM_REBOOT = 0

  # Authorization Action
  ACTION_CODE_AUTH_TOKEN = 0
  ACTION_CODE_AUTH_RESULT = 7

  # Card Reader Action
  ACTION_CODE_RFID_NUMBER = 0
  ACTION_CODE_RFID_DATA = 1
  ACTION_CODE_RFID_RESULT_JSON = 6
  ACTION_CODE_RFID_RESULT_STRING = 7

  # Buzzer Action
  ACTION_CODE_BUZZER_SOUND = 0
end
